---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kushmaar/public_html/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R .well-known $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R CSS $DEPLOYPATH
    - /bin/cp -R db_images $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R JS $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp album.php $DEPLOYPATH
    - /bin/cp blog.php $DEPLOYPATH
    - /bin/cp donate.html $DEPLOYPATH
    - /bin/cp donate.php $DEPLOYPATH
    - /bin/cp doners.html $DEPLOYPATH
    - /bin/cp doners.php $DEPLOYPATH
    - /bin/cp error_log $DEPLOYPATH
    - /bin/cp event.php $DEPLOYPATH
    - /bin/cp events.php $DEPLOYPATH
    - /bin/cp gallery.php $DEPLOYPATH
    - /bin/cp googled610fff1837acdfc.html $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp post.php $DEPLOYPATH    